server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/baseTelegramBot
spring.datasource.username=myTelegramAdmin
spring.datasource.password=123
telegram.bot.token=8639153673:AAFw_FxqEU_o4BDFcovKA7HbC8FKTjIWUkE
spring.liquibase.change-log=classpath:liquibase/changelog/db.changelog-master.yaml